import { Order, OrderItem } from '../types/database';

/**
 * Mock orders data with various statuses
 * Requirements: 6.1, 7.5
 */
export const mockOrders: Order[] = [
  {
    id: 'order-1',
    order_number: 'SW2024010001',
    parent_id: 'user-1',
    status: 'confirmed',
    payment_method: 'bank_transfer',
    payment_deadline: new Date('2024-02-10').toISOString(),
    payment_proof_url: '/uploads/payment-proof-1.jpg',
    total_amount: 5600,
    discount_amount: 0,
    final_amount: 5600,
    group_code: null,
    notes: '',
    created_at: new Date('2024-01-15').toISOString(),
    updated_at: new Date('2024-01-16').toISOString(),
  },
  {
    id: 'order-2',
    order_number: 'SW2024010002',
    parent_id: 'user-1',
    status: 'pending_payment',
    payment_method: 'bank_transfer',
    payment_deadline: new Date('2024-02-20').toISOString(),
    payment_proof_url: null,
    total_amount: 5600,
    discount_amount: 280,
    final_amount: 5320,
    group_code: 'FAMILY2024',
    notes: '希望兩個孩子在同一時段',
    created_at: new Date('2024-02-15').toISOString(),
    updated_at: new Date('2024-02-15').toISOString(),
  },
  {
    id: 'order-3',
    order_number: 'SW2024010003',
    parent_id: 'user-2',
    status: 'payment_submitted',
    payment_method: 'line_pay',
    payment_deadline: new Date('2024-02-25').toISOString(),
    payment_proof_url: '/uploads/payment-proof-3.jpg',
    total_amount: 9600,
    discount_amount: 960,
    final_amount: 8640,
    group_code: null,
    notes: '',
    created_at: new Date('2024-02-20').toISOString(),
    updated_at: new Date('2024-02-21').toISOString(),
  },
  {
    id: 'order-4',
    order_number: 'SW2024010004',
    parent_id: 'user-3',
    status: 'cancelled_manual',
    payment_method: 'bank_transfer',
    payment_deadline: new Date('2024-02-05').toISOString(),
    payment_proof_url: null,
    total_amount: 2800,
    discount_amount: 0,
    final_amount: 2800,
    group_code: null,
    notes: '家庭行程衝突，申請取消',
    created_at: new Date('2024-01-28').toISOString(),
    updated_at: new Date('2024-02-01').toISOString(),
  },
];

export const mockOrderItems: OrderItem[] = [
  // Order 1 items
  {
    id: 'item-1',
    order_id: 'order-1',
    session_id: '1',
    child_id: 'child-1',
    price: 2800,
    discount_amount: 0,
    created_at: new Date('2024-01-15').toISOString(),
  },
  {
    id: 'item-2',
    order_id: 'order-1',
    session_id: '2',
    child_id: 'child-1',
    price: 2800,
    discount_amount: 0,
    created_at: new Date('2024-01-15').toISOString(),
  },
  // Order 2 items
  {
    id: 'item-3',
    order_id: 'order-2',
    session_id: '1',
    child_id: 'child-1',
    price: 2800,
    discount_amount: 140,
    created_at: new Date('2024-02-15').toISOString(),
  },
  {
    id: 'item-4',
    order_id: 'order-2',
    session_id: '1',
    child_id: 'child-2',
    price: 2800,
    discount_amount: 140,
    created_at: new Date('2024-02-15').toISOString(),
  },
  // Order 3 items
  {
    id: 'item-5',
    order_id: 'order-3',
    session_id: '2',
    child_id: 'child-3',
    price: 3200,
    discount_amount: 320,
    created_at: new Date('2024-02-20').toISOString(),
  },
  {
    id: 'item-6',
    order_id: 'order-3',
    session_id: '4',
    child_id: 'child-3',
    price: 2900,
    discount_amount: 290,
    created_at: new Date('2024-02-20').toISOString(),
  },
  {
    id: 'item-7',
    order_id: 'order-3',
    session_id: '5',
    child_id: 'child-4',
    price: 3200,
    discount_amount: 320,
    created_at: new Date('2024-02-20').toISOString(),
  },
  // Order 4 items
  {
    id: 'item-8',
    order_id: 'order-4',
    session_id: '3',
    child_id: 'child-5',
    price: 2800,
    discount_amount: 0,
    created_at: new Date('2024-01-28').toISOString(),
  },
  // Battle of Kadal (session 2) role assignments for testing
  {
    id: 'item-9',
    order_id: 'order-1',
    session_id: '2',
    child_id: 'child-1',
    price: 3200,
    discount_amount: 0,
    role_id: 'aileen',
    created_at: new Date('2024-01-15').toISOString(),
  },
  {
    id: 'item-10',
    order_id: 'order-3',
    session_id: '2',
    child_id: 'child-3',
    price: 3200,
    discount_amount: 320,
    role_id: 'litt',
    created_at: new Date('2024-02-20').toISOString(),
  },
];
